FoodApp/Controllers/CafeController.cs
using System.Threading.Tasks;
using FoodApp.Core.Models;
using Microsoft.AspNetCore.Mvc;
using FoodApp.DAL;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Routing;

namespace FoodApp.Controllers
{
    [Authorize]
    public class CafeController : Controller
    {
        private readonly IUnitOfWorkFactory _unitOfWorkFactory;

        public CafeController(IUnitOfWorkFactory unitOfWorkFactory)
        {
            _unitOfWorkFactory = unitOfWorkFactory;
        }

        public IActionResult Index()
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                var cafes = unitOfWork.Cafe.GetAll();
                return View(cafes);
            }
        }

        public async Task<IActionResult> Details(int? id)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                if (!id.HasValue)
                {
                    return NotFound();
                }

                var cafe = unitOfWork.Cafe.GetById(id.Value);
                if (cafe == null)
                {
                    return NotFound();
                }

                var orders = unitOfWork.Order.GetAll();
                return View(cafe);
            }
        }

        [Authorize(Roles = "Client")]
        public async Task<IActionResult> Review(int? id)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork()) {

                if (!id.HasValue)
                {
                    return NotFound();
                }

                var cafe = unitOfWork.Cafe.GetById(id.Value);
                if (cafe == null)
                {
                    return NotFound();
                }


                var review = new Review
                {
                    Rating = 2,
                    Comment = "qweq",
                    Cafe = cafe,
                };
                await unitOfWork.Review.AddAsync(review);
                await unitOfWork.CompleteAsync();

                return RedirectToAction("Details", new RouteValueDictionary(review));
            }
        }



    }
}

FoodApp/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using FoodApp.Core.Models;
using FoodApp.DAL;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FoodApp.Controllers
{
    [Authorize(Roles = "Client")]
    public class ShoppingCartController : Controller
    {
        private readonly IUnitOfWorkFactory _unitOfWorkFactory;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public ShoppingCartController(IUnitOfWorkFactory unitOfWorkFactory, IHttpContextAccessor httpContextAccessor)
        {
            _unitOfWorkFactory = unitOfWorkFactory;
            _httpContextAccessor = httpContextAccessor;
        }

        public async Task<IActionResult> AddToCart(int id)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                var userName = _httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.Name);
                var cart = unitOfWork.ShoppingCart.GetByName(userName);
                var dish = unitOfWork.Dish.GetById(id);
                var cartItems = unitOfWork.CartItem.GetByCartId(cart.Id);
                CartItem line = unitOfWork.CartItem.GetById(id);
                if (line == null)
                {
                    line = new CartItem
                    {
                        Dish = dish,
                        Quanity = 1,

                    };
                }
                else
                {
                    line.Quanity += 1;
                }

                var total = 0;
                foreach (var item in cartItems)
                {
                    total += (item.Quanity * item.Dish.Price);
                }

                cart.SubtotalPrice = total;
                cart.CartItems.Add(line);
                unitOfWork.ShoppingCart.Update(cart);
                await unitOfWork.CompleteAsync();
                return RedirectToAction(nameof(Basket));
            }

        }

        public async Task<IActionResult> Basket()
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                var userName = _httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.Name);
                var cart = unitOfWork.ShoppingCart.GetByName(userName);
                var cartItems = unitOfWork.CartItem.GetByCartId(cart.Id);
                return View(cartItems);
            }
        }

        public async Task<IActionResult> CreateOrder(Order order)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                
                order.OrderTime = DateTime.Now;
                return View(order);
            }
        }

        public async Task<IActionResult> Checkout(Order order)
        {
            using (var unitOfWork = _unitOfWorkFactory.MakeUnitOfWork())
            {
                var userName = _httpContextAccessor.HttpContext.User.FindFirstValue(ClaimTypes.Name);
                var cart = unitOfWork.ShoppingCart.GetByName(userName);
                var cartItems = unitOfWork.CartItem.GetByCartId(cart.Id);

                var total = 0;
                foreach (var item in cartItems)
                {
                    var orderDetail = new OrderDetail
                    {
                        Quanity = item.Quanity,
                        Dish = item.Dish,
                        Order = order
                    };
                    total += (item.Quanity * item.Dish.Price);
                    order.OrderDetails.Add(orderDetail);
                    await unitOfWork.OrderDetail.AddAsync(orderDetail);
                    await unitOfWork.CompleteAsync();
                    unitOfWork.CartItem.Delete(item);
                    await unitOfWork.CompleteAsync();
                }
                order.TotalOrderPrice = total;
                unitOfWork.Order.Update(order);
                await unitOfWork.CompleteAsync();
                return RedirectToAction("ConfirmOrder");
            }
        }

        public IActionResult ConfirmOrder()
        {
            return View("ConfirmOrder");
        }
    }
}

FoodApp/Views/Cafe/Details.cshtml
@using FoodApp.Core.Models
@using FoodApp.Enums
@model Cafe

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Shop Item - Start Bootstrap Template</title>

</head>
<body>

<!-- Page Content -->
<div class="container">
    <div class="row">

        <!-- /.col-lg-3 -->
        <div class="col-lg-12">
            <div class="card mt-4">
                <img class="card-img-top img-fluid" src="http://placehold.it/900x400" alt="">
                <div class="card-body">
                    <h3 class="card-title">@Model.Name</h3>
                    <p class="card-text">@Model.Description</p>
                    <span class="text-warning">Средняя оценка заведения: </span>
                </div>
            </div>
            <!-- /.card -->
            @if (User.IsInRole(Roles.Client.ToString()))
            {
                <div class="col-lg-4">
                    <div class="card mt-4">
                        <div class="card-body">
                            <a asp-controller="ShoppingCart" asp-action="Basket" asp-route-id="@Model.Id">Корзина</a>
                        </div>
                    </div>
                </div>
            }
            <div class="card-body"></div>
            <div class="row">

                @foreach (var dish in Model.Dishes)
                {
                    <div class="col-lg-3 col-md-6 mb-3">
                        <div class="card h-100">
                            <a href="#">
                                <img class="card-img-top" src="http://placehold.it/700x400" alt="">
                            </a>
                            <div class="card-body">
                                <h4 class="card-title">
                                    <a href="#">@dish.Name</a>
                                </h4>
                                <h5>@dish.Price сом</h5>
                                <p class="card-text">@dish.Description</p>
                            </div>
                            @if (User.IsInRole(Roles.Client.ToString()))
                            {
                                <div class="card-body">
                                    <a asp-controller="ShoppingCart" asp-action="AddToCart" asp-route-id="@dish.Id" class="btn btn-success">Добавить в корзину <i class="fa fa-beer"></i></a>
                                </div>
                            }
                        </div>
                    </div>
                }
            </div>

            <div class="card card-outline-secondary my-4">
                <div class="card-header">
                    Отзывы
                </div>
                <div class="card-body">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis et enim aperiam inventore, similique necessitatibus neque non! Doloribus, modi sapiente laboriosam aperiam fugiat laborum. Sequi mollitia, necessitatibus quae sint natus.</p>
                    <small class="text-muted">Оценка 5</small>
                    <hr>
                    @if (User.IsInRole(Roles.Client.ToString()))
                    {
                        <div class="row">
                            <div class="col-md-4">

                                <div class="form-group">
                                    <a asp-controller="Cafe" asp-action="Review" asp-route-id="@Model.Id">Оставить отзыв</a>
                                </div>
                            </div>

                        </div>
                    }
                </div>
            </div>

            <!-- /.card -->
        </div>
        <!-- /.col-lg-9 -->
    </div>
</div>
<!-- /.container -->

</body>
</html>

FoodApp/Views/Cafe/Index.cshtml
@model IEnumerable<FoodApp.Core.Models.Cafe>

@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Shop Homepage - Start Bootstrap Template</title>
</head>
<body>

<!-- Page Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-3">
            <h1 class="my-4">Shop Name</h1>
            @foreach (var cafe in Model)
            {
            <div class="list-group">
                <a class="list-group-item" asp-action="Details" asp-route-id="@cafe.Id">@cafe.Name</a>
            </div>
            }
        </div>
        <!-- /.col-lg-3 -->
        <div class="col-lg-9">

            <div class="row">
                @foreach (var cafe in Model)
                {
                    <div class="col-lg-4 col-md-6 mb-4">
                        <div class="card h-100">
                            <a asp-action ="Details" asp-route-id="@cafe.Id">
                                <img class="card-img-top" src="http://placehold.it/700x400" alt="">
                            </a>
                            <div class="card-body">
                                <h4 class="card-title">
                                    <a asp-action ="Details" asp-route-id="@cafe.Id">@cafe.Name</a>
                                </h4>
                                <p class="card-text">@cafe.Description</p>
                            </div>

                        </div>
                    </div>
                }
            </div>
            <!-- /.row -->
        </div>
        <!-- /.col-lg-9 -->
    </div>
    <!-- /.row -->
</div>
<!-- /.container -->
</body>
</html>

FoodApp/Views/Cafe/Review.cshtml
@model FoodApp.Core.Models.Review

@{
    ViewData["Title"] = "View";
}

<h1>View</h1>

<h4>Review</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="View">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comment" class="control-label"></label>
                <input asp-for="Comment" class="form-control" />
                <span asp-validation-for="Comment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CafeId" class="control-label"></label>
                <select asp-for="CafeId" class ="form-control" asp-items="ViewBag.CafeId"></select>
            </div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class ="form-control" asp-items="ViewBag.UserId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>